export enum Role {
  USER = "USER",
  ADMIN = "ADMIN", // Legacy/General Admin
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN_PRODUK = "ADMIN_PRODUK",
  ADMIN_PESANAN = "ADMIN_PESANAN",
  ADMIN_KEUANGAN = "ADMIN_KEUANGAN",
  CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
}
